import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase'

// POST /api/green/lots — create a new green lot + initial 'received' transaction
export async function POST(req: NextRequest) {
  let body: {
    name: string
    origin: string
    producer?: string | null
    harvest_year?: string | null
    process?: string | null
    location?: string
    origin_warehouse?: string | null
    bag_count: number
    bag_weight_lbs: number
    price_per_lb?: number | null
    notes?: string | null
  }

  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const { name, origin, bag_count, bag_weight_lbs } = body

  if (!name?.trim())   return NextResponse.json({ error: 'name is required' }, { status: 400 })
  if (!origin?.trim()) return NextResponse.json({ error: 'origin is required' }, { status: 400 })
  if (!bag_count || bag_count <= 0)      return NextResponse.json({ error: 'bag_count must be > 0' }, { status: 400 })
  if (!bag_weight_lbs || bag_weight_lbs <= 0) return NextResponse.json({ error: 'bag_weight_lbs must be > 0' }, { status: 400 })

  const total = bag_count * bag_weight_lbs
  const supabase = createServerSupabaseClient()

  // Insert the lot (lot_number auto-generated by trigger)
  const { data: lot, error: lotErr } = await supabase
    .from('green_lots')
    .insert({
      lot_number:         '',   // trigger overwrites this
      name:               name.trim(),
      origin:             origin.trim(),
      producer:           body.producer ?? null,
      harvest_year:       body.harvest_year ?? null,
      process:            body.process ?? null,
      location:           body.location?.trim() || 'Roastery',
      origin_warehouse:   body.origin_warehouse ?? null,
      bag_count,
      bag_weight_lbs,
      bags_at_warehouse:  body.origin_warehouse ? bag_count : 0,
      bags_at_roastery:   body.origin_warehouse ? 0 : bag_count,
      total_weight_lbs:   total,
      initial_weight_lbs: total,
      price_per_lb:       body.price_per_lb ?? null,
      notes:              body.notes ?? null,
      status:             'active',
    })
    .select()
    .single()

  if (lotErr) {
    console.error('green_lots insert error:', lotErr)
    return NextResponse.json({ error: lotErr.message }, { status: 500 })
  }

  // Log initial 'received' transaction
  const { error: txErr } = await supabase
    .from('green_lot_transactions')
    .insert({
      green_lot_id: lot.id,
      type:         'received',
      weight_lbs:   total,
      notes:        `Initial receipt — ${bag_count} bag${bag_count !== 1 ? 's' : ''} × ${bag_weight_lbs} lbs`,
    })

  if (txErr) {
    // Non-fatal — lot was created; log the error but don't fail the request
    console.error('green_lot_transactions insert error (initial received):', txErr)
  }

  return NextResponse.json(lot, { status: 201 })
}
